services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    
    environment:
      MYSQL_ROOT_PASSWORD: Tharun@1234
      MYSQL_DATABASE: projectfinaldb
      # app.prop : Db = SDPDB-35
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # volume added here

  backend:
    container_name: back
    build:
    
      context: ./springbootbackend
      dockerfile: backend.Dockerfile
    image: back
    ports:
      - "2025:2000" # edo okati testing 
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: front
    build:
      context: ./reactfrontend
      dockerfile: frontend.Dockerfile
    image: front
    ports:
      - "3000:80"
    depends_on:
      - backend

# Declare volumes at the bottom
volumes:
  mysql-data: